[package]
name = "redis-pubsub"
version = "0.1.0"
authors = ["William McAdams <musicpulpite@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
